apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/wise-imagery-440722-p7/locations/us-central1-c/clusters/cluster-1

